spring.application.name=AIDemo
server.port = 8080

spring.ai.mcp.sever.name=shobhitMcp
spring.ai.mcp.server.version=0.1.1

#MCP configuration

spring.ai.mcp.sever.sse=false
spring.ai.mcp.sever.protocol=streamable
spring.ai.mcp.sever.stdio=false
spring.ai.mcp.sever.type=sync